// ─────────────────────────────────────────────────────────────────────────────
// state.rs — shared runtime state and the orchestrator control channel.
//
// One `AppState` is shared (Arc) across the control HTTP server, the transport
// task, and the discovery task. Mutations go through async RwLocks; the
// orchestrator owns the session lifecycle via the `ctrl` mpsc channel.
// ─────────────────────────────────────────────────────────────────────────────

use crate::adapters::osc::OscAdapter;
use crate::config::Config;
use serde::Serialize;
use std::sync::Arc;
use tokio::sync::{mpsc, RwLock};
use webrtc::ice_transport::ice_server::RTCIceServer;

/// Live status surfaced to the control UI.
#[derive(Clone, Debug, Default, Serialize)]
pub struct Status {
    pub paired: bool,
    pub session_id: Option<String>,
    pub connected: bool,
    pub ended: bool,
    pub last_error: Option<String>,
    pub frames_in: u64,
    pub messages_out: u64,
    /// Wall-clock ms of the last inbound frame.
    pub last_frame_ms: Option<u64>,
    /// The pairing code shown to the user (generated by bridge, entered in cloud).
    pub pairing_code: String,
}

/// A locally discovered OSC-capable destination (mDNS `_osc._udp`).
#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct Discovered {
    pub name: String,
    pub host: String,
    pub port: u16,
}

/// Commands handled by the orchestrator loop.
#[derive(Debug)]
pub enum Ctrl {
    /// Connect using a session code (the rendezvous room shared with the
    /// browser peer) and open the WebRTC data channel.
    Connect(String),
    /// Tear down the current peer connection and forget the session.
    Disconnect,
    /// Re-read OSC destination from config and retarget the adapter.
    ReloadOsc,
    /// Generate a new pairing code and update status.
    RegenerateCode,
}

pub struct AppState {
    pub config: RwLock<Config>,
    pub status: RwLock<Status>,
    pub osc: Arc<OscAdapter>,
    pub discovered: RwLock<Vec<Discovered>>,
    pub ctrl: mpsc::Sender<Ctrl>,
    /// ICE servers for the current cloud session (STUN/TURN), as returned by
    /// `POST /v1/webrtc/session`. Empty until a session is created.
    pub ice_servers: RwLock<Vec<RTCIceServer>>,
}

impl AppState {
    pub async fn snapshot_status(&self) -> Status {
        self.status.read().await.clone()
    }
}
