// ─────────────────────────────────────────────────────────────────────────────
// state.rs — shared runtime state and the orchestrator control channel.
//
// One `AppState` is shared (Arc) across the control HTTP server, the transport
// task, and the discovery task. Mutations go through async RwLocks; the
// orchestrator owns the session lifecycle via the `ctrl` mpsc channel.
// ─────────────────────────────────────────────────────────────────────────────

use crate::adapters::osc::OscAdapter;
use crate::config::Config;
use serde::Serialize;
use std::sync::Arc;
use tokio::sync::{mpsc, oneshot, Mutex, RwLock};
use webrtc::ice_transport::ice_server::RTCIceServer;

/// What we can tell the user about the peer that is trying to connect, so they
/// can make an informed accept/decline decision. Everything here is best-effort:
/// some fields come from optional metadata the peer supplies through signaling,
/// the network addresses are parsed out of the offer's ICE candidates.
#[derive(Clone, Debug, Default, Serialize, PartialEq)]
pub struct PeerInfo {
    /// Friendly name the peer chose to present (if any).
    pub name: Option<String>,
    /// Web origin the offer came from (e.g. `https://app.pieeg.com`).
    pub origin: Option<String>,
    /// Browser/user-agent string reported by the peer (if any).
    pub user_agent: Option<String>,
    /// Remote IP addresses seen in the offer's ICE candidates.
    pub ip_addresses: Vec<String>,
    /// ICE candidate types present in the offer (host / srflx / relay …).
    pub candidate_types: Vec<String>,
    /// Wall-clock ms when the request arrived.
    pub requested_ms: u64,
}

/// Live status surfaced to the control UI.
#[derive(Clone, Debug, Default, Serialize)]
pub struct Status {
    pub paired: bool,
    pub session_id: Option<String>,
    pub connected: bool,
    pub ended: bool,
    pub last_error: Option<String>,
    pub frames_in: u64,
    pub messages_out: u64,
    /// Wall-clock ms of the last inbound frame.
    pub last_frame_ms: Option<u64>,
    /// The pairing code shown to the user (generated by bridge, entered in cloud).
    pub pairing_code: String,
    /// True while a peer is waiting for the user to accept or decline the
    /// connection. The UI shows a confirmation prompt with `pending_peer`.
    pub awaiting_confirmation: bool,
    /// Details about the peer awaiting confirmation (only set while
    /// `awaiting_confirmation` is true).
    pub pending_peer: Option<PeerInfo>,
    /// True once the user has explicitly accepted the current session, so
    /// reconnects within the same session don't re-prompt.
    pub confirmed: bool,
}

/// A locally discovered OSC-capable destination (mDNS `_osc._udp`).
#[derive(Clone, Debug, Serialize, PartialEq)]
pub struct Discovered {
    pub name: String,
    pub host: String,
    pub port: u16,
}

/// Commands handled by the orchestrator loop.
#[derive(Debug)]
pub enum Ctrl {
    /// Connect using a session code (the rendezvous room shared with the
    /// browser peer) and open the WebRTC data channel.
    Connect(String),
    /// Tear down the current peer connection and forget the session.
    Disconnect,
    /// Re-read OSC destination from config and retarget the adapter.
    ReloadOsc,
    /// Generate a new pairing code and update status.
    RegenerateCode,
}

pub struct AppState {
    pub config: RwLock<Config>,
    pub status: RwLock<Status>,
    pub osc: Arc<OscAdapter>,
    pub discovered: RwLock<Vec<Discovered>>,
    pub ctrl: mpsc::Sender<Ctrl>,
    /// ICE servers for the current cloud session (STUN/TURN), as returned by
    /// `POST /v1/webrtc/session`. Empty until a session is created.
    pub ice_servers: RwLock<Vec<RTCIceServer>>,
    /// When a peer is awaiting confirmation, the transport parks a one-shot
    /// sender here; the control API fires it with the user's accept/decline
    /// decision. `None` when no request is pending.
    pub pending_decision: Mutex<Option<oneshot::Sender<bool>>>,
}

impl AppState {
    pub async fn snapshot_status(&self) -> Status {
        self.status.read().await.clone()
    }

    /// Deliver the user's accept/decline decision to a peer waiting for
    /// confirmation. Returns `true` if a request was actually pending.
    pub async fn resolve_pending(&self, accept: bool) -> bool {
        if let Some(tx) = self.pending_decision.lock().await.take() {
            let _ = tx.send(accept);
            true
        } else {
            false
        }
    }
}
